extends Node

# Spec 26 — combat SFX player (autoloaded as `Sfx`). A small pool of
# AudioStreamPlayers so rapid hits don't cut each other off; per-play pitch
# jitter so repeats don't feel mechanical. Sound files (ElevenLabs-generated)
# live in res://audio/; if one is missing, play() is a graceful no-op.

const PATHS := {
	"fire":        "res://audio/fire.mp3",
	"hit":         "res://audio/hit.mp3",
	"crit":        "res://audio/crit.mp3",
	"death":       "res://audio/enemy_death.mp3",
	"pickup":      "res://audio/pickup.mp3",       # spec 27f
	"equip":       "res://audio/equip.mp3",        # spec 27f
	"inv_open":    "res://audio/inv_open.mp3",     # spec 27f
	"inv_full":    "res://audio/inv_full.mp3",     # pack-full pickup cue
	# Spec 29 — interactable SFX. The files are deferred (the ElevenLabs
	# spend wasn't pre-approved); play() is a graceful no-op until they land.
	"chest_open":  "res://audio/chest_open.mp3",
	"shrine_bless": "res://audio/shrine_bless.mp3",
	"hearth_rest": "res://audio/hearth_rest.mp3",
	# Spec 30 — skill SFX. Files deferred (~$0.30 ElevenLabs spend pending).
	"skill_power": "res://audio/skill_power.mp3",
	"skill_multi": "res://audio/skill_multi.mp3",
	"skill_snare": "res://audio/skill_snare.mp3",
	"skill_rain_of_thorns": "res://audio/skill_rain_of_thorns.mp3",
	"thornburst_impact":    "res://audio/thornburst_impact.mp3",
	# B8 — gather channels, sustain, crafting, bosses, transitions.
	# Generated by tools/generate_audio.py (ElevenLabs); no-ops until then.
	"mine":        "res://audio/mine.mp3",
	"chop":        "res://audio/chop.mp3",
	"forage":      "res://audio/forage.mp3",
	"quaff":       "res://audio/quaff.mp3",
	"craft_cook":  "res://audio/craft_cook.mp3",
	"craft_smith": "res://audio/craft_smith.mp3",
	"craft_still": "res://audio/craft_still.mp3",
	"regrow_pop":          "res://audio/regrow_pop.mp3",
	"town_arrival_swell":  "res://audio/town_arrival_swell.mp3",
	"town_ambient_birds":  "res://audio/town_ambient_birds.mp3",
	"town_fire_crackle":   "res://audio/town_fire_crackle.mp3",
	"level_up":    "res://audio/level_up.mp3",
	"telegraph":   "res://audio/telegraph.mp3",
	"charge":      "res://audio/charge.mp3",
	"lunge":       "res://audio/lunge.mp3",
	"roll":        "res://audio/roll.mp3",
	"waystone":    "res://audio/waystone.mp3",
	# Wayfinding signature — the inscription seal. File deferred (ElevenLabs
	# spend ungated); play() is a graceful no-op until it lands.
	"inscribe_seal": "res://audio/inscribe_seal.mp3",
}

# B8 — one looping music/ambience channel (the town theme). Separate from
# the one-shot pool so a jingle never cuts the theme.
const MUSIC_PATHS := {
	"town_theme": "res://audio/town_theme.mp3",
}
const POOL := 8

var _streams := {}
var _players: Array = []
var _next := 0
var _music: AudioStreamPlayer = null
var _music_key := ""


func _ready() -> void:
	for key in PATHS:
		if ResourceLoader.exists(PATHS[key]):
			_streams[key] = load(PATHS[key])
	for _i in POOL:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)
	_music = AudioStreamPlayer.new()
	_music.volume_db = -8.0
	add_child(_music)

# Start (or keep) the named loop; unknown/missing names stop the music.
func music(name: String) -> void:
	if name == _music_key and _music.playing:
		return
	_music_key = name
	var path := String(MUSIC_PATHS.get(name, ""))
	if path == "" or not ResourceLoader.exists(path):
		_music.stop()
		return
	var stream = load(path)
	if stream is AudioStreamMP3:
		stream.loop = true
	_music.stream = stream
	_music.play()

func stop_music() -> void:
	_music_key = ""
	_music.stop()

func play(name: String, pitch_var := 0.07) -> void:
	if not _streams.has(name) or _players.is_empty():
		return
	var p: AudioStreamPlayer = _players[_next]
	_next = (_next + 1) % _players.size()
	p.stream = _streams[name]
	p.pitch_scale = 1.0 + randf_range(-pitch_var, pitch_var)
	p.play()
